apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-frontend
  name: udagram-frontend-svc
spec:
  ports:
  - port: 8100
    protocol: TCP
    targetPort: 8100
  selector:
    service: udagram-frontend